### ISSUE TITLE
BE- random sandwich generation

### ISSUE THREAD

**Issue by IsaacFigNewton** [IsaacFigNewton/SandoMatch#10]
Estimate: 2.5hrs

Update restaurant ingredients calorie information
Add a list of restaurant tags to newly generated sandwich objects
Add a list of restaurant costs to new sandwiches
Add new sandwich objects to the sandwiches table

Example Pseudocode:

Determine cost based on ingredients in the **restaurant_ingredients** table:
1. generate a sandwich using ingredients from the "default" entry in the restaurant_ingredients table
2. if the ingredients in the generated sandwich ingredient combo can be found in the "mr_pickles" or "subway" entries of the restaurant_ingredients table
    1. check if there's already a sandwich with the generated ingredient combination  associated with the restaurant in the **sandwiches** table there
        1. if there is one there, return that
    2. create separate sandwich entries for each restaurant with said ingredients
        1. determine cost, calorie count for different sandwich entries based off of the respective ingredient fields in the associated **restaurant_ingredients** entries
        2. return both entries
3. otherwise, the restaurant tag list should be empty
    1. create 1 sandwich entry using the calorie and cost information in the "default" entry of the restaurant_ingredients table
    2. return that sandwich
4. determine dietary tags based on the generated sandwich's ingredients

**Comment by mmgout** [comment]
Estimated Time: 1 hour

**Comment by IsaacFigNewton** [comment]
Resolving merge conflicts and associated bugs - 2hrs
