### ISSUE TITLE
DB - Sandwich entry fields

### ISSUE THREAD

**Issue by IsaacFigNewton** [IsaacFigNewton/SandoMatch#2]
- Id
- Sando Name 
- List of ingredients, amount pairs (minimum of 1)
    - Ingredients are json objects themselves, with subids denoting specific type
- Cost
- Calorie count
- Average rating
    - Number of ratings
- Dietary tags:
    - Vegan
    - Vegetarian
    - Gluten-Free
    - Dairy-free
    - etc. Tags

**Comment by mmgout** [comment]
Estimated Time: 1 hour, 15 minutes
