### ISSUE TITLE
BE - Link BE to DB for sando CRUD

### ISSUE THREAD

**Issue by IsaacFigNewton** [IsaacFigNewton/SandoMatch#42]
Estimate: 4hrs

Allow new sandwich DB entry creation
- Link to Isai's random sandwich generating code

Enable sando object retrieval
- Load full sando profile on backend
- Send full sando object to the frontend for a sando request

Allow sando review-related updates:
- Append review object id to the reviews list field
- Update the average rating field

Never need to delete a sando

**Comment by mmgout** [comment]
Note that this issue was abandoned due to problems with merge conflicts. The project worked fine without being connected to Mongo, and we didn't want to risk it as we were running short on time.
